package org.smartbank.client.model;

import java.time.LocalDateTime;

public class Transaction {
    private int transactionId;        // Auto-generated by the database
    private String transactionType;   // Type of transaction
    private double amount;            // Amount involved
    private Integer fromUserId;       // Sender (nullable for deposits)
    private Integer toUserId;         // Recipient (nullable for withdrawals)
    private LocalDateTime date;       // Transaction timestamp

    // Constructor for creating a transaction with an auto-generated ID
    public Transaction(String transactionType, double amount, Integer fromUserId, Integer toUserId, LocalDateTime date) {
        this.transactionType = transactionType;
        this.amount = amount;
        this.fromUserId = fromUserId;
        this.toUserId = toUserId;
        this.date = date;
    }

    // Constructor for retrieving a transaction with an existing ID
    public Transaction(int transactionId, String transactionType, double amount, Integer fromUserId, Integer toUserId, LocalDateTime date) {
        this.transactionId = transactionId;
        this.transactionType = transactionType;
        this.amount = amount;
        this.fromUserId = fromUserId;
        this.toUserId = toUserId;
        this.date = date;
    }

    // Getters and Setters
    public int getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(int transactionId) {
        this.transactionId = transactionId;
    }

    public String getTransactionType() {
        return transactionType;
    }

    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public Integer getFromUserId() {
        return fromUserId;
    }

    public void setFromUserId(Integer fromUserId) {
        this.fromUserId = fromUserId;
    }

    public Integer getToUserId() {
        return toUserId;
    }

    public void setToUserId(Integer toUserId) {
        this.toUserId = toUserId;
    }

    public LocalDateTime getDate() {
        return date;
    }

    public void setDate(LocalDateTime date) {
        this.date = date;
    }

    @Override
    public String toString() {
        return "Transaction{" +
                "transactionId=" + transactionId +
                ", transactionType='" + transactionType + '\'' +
                ", amount=" + amount +
                ", fromUserId=" + fromUserId +
                ", toUserId=" + toUserId +
                ", date=" + date +
                '}';
    }
}
